//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CidadeSemLimites.Exception.ErrorMessagesResources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PostResource
    {

        public static global::System.Resources.ResourceManager resourceMan;

        public static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PostResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CidadeSemLimites.Exception.ErrorMessagesResources.PostResource", typeof(PostResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A data de criação não pode ser vazia.
        /// </summary>
        public static string Empty__Creation_Date
        {
            get
            {
                return ResourceManager.GetString("Empty _Creation_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O Autor não pode ser vazio
        ///.
        /// </summary>
        public static string Empty_Author
        {
            get
            {
                return ResourceManager.GetString("Empty_Author", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ser vazia.
        /// </summary>
        public static string Empty_Description
        {
            get
            {
                return ResourceManager.GetString("Empty_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O bairro não pode ser vazio.
        /// </summary>
        public static string Empty_Neighborhood
        {
            get
            {
                return ResourceManager.GetString("Empty_Neighborhood", resourceCulture);
            }
        }
    }
}
